### ISSUE TITLE
Unable to rewrite relative urls

### ISSUE THREAD

**Issue by DrewCerny** [mat-sz/lettersanitizer#2]
I am using this in conjunction with react-letter. My back end email processor provides email bodies with images with relative urls. It would be useful if I could rewrite relative urls like I can for external ones.

**Comment by mat-sz** [comment]
Resolved in a9991c74d3de8955ee6dc3c6f18258b456b4780d. I'll update the issue when a new version will be released.

**Comment by mat-sz** [comment]
Resolved in 1.0.3.
