### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by david9100** [mat-sz/lettersanitizer#3]
I get the following when trying to use the Letter and extract components:

```
./node_modules/lettersanitizer/lib/index.js 65:20
Module parse failed: Unexpected token (65:20)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   let node;
|   while (node = commentIter.nextNode()) {
>     node.parentNode?.removeChild(node);
|   }
|   const removeTags = [...removeWithContents];

```

**Comment by mat-sz** [comment]
@david9100 Your Babel configuration likely doesn't support new ECMAScript syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
Could you tell me more about your setup? What Babel version are you using, did you use any generators (create-react-app?) to bootstrap the project? What React version are you using, if any?
Most likely this issue can be resolved by updating React and react-scripts if you're using CRA, or by updating Babel and making sure it's configured to support modern ECMAScript syntax.

**Comment by david9100** [comment]
@mat-sz Thanks for the quick follow up.  I'm using a react app starter I purchased from Bootstrap.  My package.json is as follows:

{
  "name": "hyper-react",
  "version": "3.0.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.2",
    "@fortawesome/free-solid-svg-icons": "^6.1.2",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@fullcalendar/bootstrap": "^5.7.2",
    "@fullcalendar/core": "^5.7.2",
    "@fullcalendar/daygrid": "^5.7.2",
    "@fullcalendar/interaction": "^5.7.2",
    "@fullcalendar/list": "^5.7.2",
    "@fullcalendar/react": "^5.7.0",
    "@fullcalendar/timegrid": "^5.7.2",
    "@hookform/resolvers": "^2.8.5",
    "@reduxjs/toolkit": "^1.8.3",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "apexcharts": "^3.33.0",
    "axios": "^0.24.0",
    "base64-js": "^1.5.1",
    "bootstrap": "^5.1.3",
    "britecharts-react": "^0.5.4",
    "chart.js": "^3.7.0",
    "classnames": "^2.3.1",
    "draft-js": "^0.11.5",
    "draftjs-to-html": "^0.9.1",
    "frappe-gantt": "^0.5.0",
    "google-maps-react": "^2.0.6",
    "http-proxy-middleware": "^2.0.1",
    "i18next": "^20.2.1",
    "i18next-browser-languagedetector": "^6.1.0",
    "jodit-react": "^1.1.17",
    "jsvectormap": "^1.3.1",
    "jwt-decode": "^3.1.2",
    "letterparser": "^0.0.10",
    "node-sass": "^5.0.0",
    "nouislider-react": "^3.3.7",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-app-polyfill": "1.0.6",
    "react-albus": "^2.0.0",
    "react-apexcharts": "^1.3.9",
    "react-beautiful-dnd": "^13.0.0",
    "react-bootstrap": "v2.0.0-alpha.2",
    "react-bootstrap-typeahead": "^5.1.4",
    "react-chartjs-2": "^2.9.0",
    "react-datepicker": "^4.1.1",
    "react-dom": "^17.0.2",
    "react-draft-wysiwyg": "^1.14.5",
    "react-dropzone": "^11.3.2",
    "react-feather": "^2.0.9",
    "react-hook-form": "^7.33.1",
    "react-html-parser": "^2.0.2",
    "react-i18next": "^11.8.12",
    "react-letter": "^0.3.1",
    "react-rating": "^2.0.5",
    "react-redux": "^7.2.3",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-select": "^5.2.2",
    "react-table": "^7.7.0",
    "react-text-mask": "^5.4.3",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "simplebar-react": "^2.3.3",
    "universal-cookie": "^4.0.4",
    "web-vitals": "^1.0.1",
    "yup": "^0.32.9",
    "yup-phone": "^1.2.19"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "flow": "flow",
    "format": "prettier --write 'src/**/*.js'"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "flow-bin": "^0.153.0",
    "prettier": "2.3.1",
    "redux-saga-test-plan": "^4.0.1"
  }
}

While babel is not specifically listed in the package.json, it appears quite a bit in my yarn.lock file.

"@babel/core@7.12.3":
  version "7.12.3"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.12.3.tgz#1b436884e1e3bff6fb1328dc02b208759de92ad8"
  integrity sha512-0qXcZYKZp3/6N2jKYVxZv0aNCsxTSVCiK72DTiTYZAu7sjg73W0/aynWjMbiGd87EQL4WyA8reiJVh92AVla9g==
  dependencies:
    "@babel/code-frame" "^7.10.4"
    "@babel/generator" "^7.12.1"
    "@babel/helper-module-transforms" "^7.12.1"
    "@babel/helpers" "^7.12.1"
    "@babel/parser" "^7.12.3"
    "@babel/template" "^7.10.4"
    "@babel/traverse" "^7.12.1"
    "@babel/types" "^7.12.1"
    convert-source-map "^1.7.0"
    debug "^4.1.0"
    gensync "^1.0.0-beta.1"
    json5 "^2.1.2"
    lodash "^4.17.19"
    resolve "^1.3.2"
    semver "^5.4.1"
    source-map "^0.5.0"

"@babel/core@^7.1.0", "@babel/core@^7.12.3", "@babel/core@^7.16.0", "@babel/core@^7.7.5", "@babel/core@^7.8.4":
  version "7.19.6"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.19.6.tgz#7122ae4f5c5a37c0946c066149abd8e75f81540f"
  integrity sha512-D2Ue4KHpc6Ys2+AxpIx1BZ8+UegLLLE2p3KJEuJRKmokHOtl49jQ5ny1773KsGLZs8MQvBidAF6yWUJxRqtKtg==
  dependencies:
    "@ampproject/remapping" "^2.1.0"
    "@babel/code-frame" "^7.18.6"
    "@babel/generator" "^7.19.6"
    "@babel/helper-compilation-targets" "^7.19.3"
    "@babel/helper-module-transforms" "^7.19.6"
    "@babel/helpers" "^7.19.4"
    "@babel/parser" "^7.19.6"
    "@babel/template" "^7.18.10"
    "@babel/traverse" "^7.19.6"
    "@babel/types" "^7.19.4"
    convert-source-map "^1.7.0"
    debug "^4.1.0"
    gensync "^1.0.0-beta.2"
    json5 "^2.2.1"
    semver "^6.3.0"

**Comment by mat-sz** [comment]
@david9100 I'd advise not to buy any starters like that in the future, as they usually are heavily outdated, best way to bootstrap React is to use [yarn create react-app](https://create-react-app.dev/docs/getting-started/), and there are many good templates for CRA.

The template you're using is one major version behind in terms of react-scripts (current version is 5.0.1). Please update react, react-scripts and react-dom to their latest versions (and if compatibility issues arise, all the other libraries as well). Unfortunately due to the extra complexity in project maintenance, older versions of software are not supported, as that would require extra time spent on testing every update.

Could you also check yarn.lock for `@babel/preset-env`? Looking through dependency chains, this package.json should download the latest version of that anyway, but seems not to.

**Comment by mat-sz** [comment]
@david9100 Upon further inspection, this looks more like a Webpack issue, updating react-scripts should resolve this anyway. Seems like 4.0.3 of react-scripts relies on Webpack 4, whereas the issue was resolved in Webpack 5.

**Comment by david9100** [comment]
didn't seem to care much for that change:

```
Compiled with problems:

ERROR in ./node_modules/htmlparser2/lib/WritableStream.js 5:13-37

Module not found: Error: Can't resolve 'buffer' in './node_modules/htmlparser2/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }


ERROR in ./node_modules/lettercoder/lib/esm/index.js 4:26-53

Module not found: Error: Can't resolve 'util' in './node_modules/lettercoder/lib/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }


ERROR in ./node_modules/letterparser/lib/esm/parser.js 6:26-53

Module not found: Error: Can't resolve 'util' in './node_modules/letterparser/lib/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }


ERROR in ./node_modules/safe-buffer/index.js 3:13-30

Module not found: Error: Can't resolve 'buffer' in './node_modules/safe-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }


```

**Comment by david9100** [comment]
"@babel/preset-env@^7.11.0", "@babel/preset-env@^7.12.1", "@babel/preset-env@^7.16.4":
  version "7.19.4"
  resolved "https://registry.yarnpkg.com/@babel/preset-env/-/preset-env-7.19.4.tgz#4c91ce2e1f994f717efb4237891c3ad2d808c94b"
  integrity sha512-5QVOTXUdqTCjQuh2GGtdd7YEhoRXBMVGROAtsBeLGIbIz3obCBIfRMT1I3ZKkMgNzwkyCkftDXSSkHxnfVf4qg==
  dependencies:
    "@babel/compat-data" "^7.19.4"
    "@babel/helper-compilation-targets" "^7.19.3"
    "@babel/helper-plugin-utils" "^7.19.0"
    "@babel/helper-validator-option" "^7.18.6"
    "@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression" "^7.18.6"
    "@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining" "^7.18.9"
    "@babel/plugin-proposal-async-generator-functions" "^7.19.1"
    "@babel/plugin-proposal-class-properties" "^7.18.6"
    "@babel/plugin-proposal-class-static-block" "^7.18.6"
    "@babel/plugin-proposal-dynamic-import" "^7.18.6"
    "@babel/plugin-proposal-export-namespace-from" "^7.18.9"
    "@babel/plugin-proposal-json-strings" "^7.18.6"
    "@babel/plugin-proposal-logical-assignment-operators" "^7.18.9"
    "@babel/plugin-proposal-nullish-coalescing-operator" "^7.18.6"
    "@babel/plugin-proposal-numeric-separator" "^7.18.6"
    "@babel/plugin-proposal-object-rest-spread" "^7.19.4"
    "@babel/plugin-proposal-optional-catch-binding" "^7.18.6"
    "@babel/plugin-proposal-optional-chaining" "^7.18.9"
    "@babel/plugin-proposal-private-methods" "^7.18.6"
    "@babel/plugin-proposal-private-property-in-object" "^7.18.6"
    "@babel/plugin-proposal-unicode-property-regex" "^7.18.6"
    "@babel/plugin-syntax-async-generators" "^7.8.4"
    "@babel/plugin-syntax-class-properties" "^7.12.13"
    "@babel/plugin-syntax-class-static-block" "^7.14.5"
    "@babel/plugin-syntax-dynamic-import" "^7.8.3"
    "@babel/plugin-syntax-export-namespace-from" "^7.8.3"
    "@babel/plugin-syntax-import-assertions" "^7.18.6"
    "@babel/plugin-syntax-json-strings" "^7.8.3"
    "@babel/plugin-syntax-logical-assignment-operators" "^7.10.4"
    "@babel/plugin-syntax-nullish-coalescing-operator" "^7.8.3"
    "@babel/plugin-syntax-numeric-separator" "^7.10.4"
    "@babel/plugin-syntax-object-rest-spread" "^7.8.3"
    "@babel/plugin-syntax-optional-catch-binding" "^7.8.3"
    "@babel/plugin-syntax-optional-chaining" "^7.8.3"
    "@babel/plugin-syntax-private-property-in-object" "^7.14.5"
    "@babel/plugin-syntax-top-level-await" "^7.14.5"
    "@babel/plugin-transform-arrow-functions" "^7.18.6"
    "@babel/plugin-transform-async-to-generator" "^7.18.6"
    "@babel/plugin-transform-block-scoped-functions" "^7.18.6"
    "@babel/plugin-transform-block-scoping" "^7.19.4"
    "@babel/plugin-transform-classes" "^7.19.0"
    "@babel/plugin-transform-computed-properties" "^7.18.9"
    "@babel/plugin-transform-destructuring" "^7.19.4"
    "@babel/plugin-transform-dotall-regex" "^7.18.6"
    "@babel/plugin-transform-duplicate-keys" "^7.18.9"
    "@babel/plugin-transform-exponentiation-operator" "^7.18.6"
    "@babel/plugin-transform-for-of" "^7.18.8"
    "@babel/plugin-transform-function-name" "^7.18.9"
    "@babel/plugin-transform-literals" "^7.18.9"
    "@babel/plugin-transform-member-expression-literals" "^7.18.6"
    "@babel/plugin-transform-modules-amd" "^7.18.6"
    "@babel/plugin-transform-modules-commonjs" "^7.18.6"
    "@babel/plugin-transform-modules-systemjs" "^7.19.0"
    "@babel/plugin-transform-modules-umd" "^7.18.6"
    "@babel/plugin-transform-named-capturing-groups-regex" "^7.19.1"
    "@babel/plugin-transform-new-target" "^7.18.6"
    "@babel/plugin-transform-object-super" "^7.18.6"
    "@babel/plugin-transform-parameters" "^7.18.8"
    "@babel/plugin-transform-property-literals" "^7.18.6"
    "@babel/plugin-transform-regenerator" "^7.18.6"
    "@babel/plugin-transform-reserved-words" "^7.18.6"
    "@babel/plugin-transform-shorthand-properties" "^7.18.6"
    "@babel/plugin-transform-spread" "^7.19.0"
    "@babel/plugin-transform-sticky-regex" "^7.18.6"
    "@babel/plugin-transform-template-literals" "^7.18.9"
    "@babel/plugin-transform-typeof-symbol" "^7.18.9"
    "@babel/plugin-transform-unicode-escapes" "^7.18.10"
    "@babel/plugin-transform-unicode-regex" "^7.18.6"
    "@babel/preset-modules" "^0.1.5"
    "@babel/types" "^7.19.4"
    babel-plugin-polyfill-corejs2 "^0.3.3"
    babel-plugin-polyfill-corejs3 "^0.6.0"
    babel-plugin-polyfill-regenerator "^0.4.1"
    core-js-compat "^3.25.1"
    semver "^6.3.0"

**Comment by david9100** [comment]
@mat-sz - Thanks for all of your help.  Along with the direction you provided, the answer was in the error message I provided above.  I simply needed to install util and buffer.
